/home/duckietown/scm/duckuments/deploy/local/lib/python2.7/site-packages/ruamel.ordereddict-0.4.9-py2.7-linux-x86_64.egg/_ordereddict.py:3: UserWarning: Module _ruamel_yaml was already imported from None, but /home/duckietown/scm/duckuments/deploy/lib/python2.7/site-packages/ruamel.yaml-0.15.16-py2.7-linux-x86_64.egg is being added to sys.path
           mcdp|note_errors_inline.py:36   - <module>       | [31m[31mFound a few errors:[0m[0m
           mcdp|note_errors_inline.py:37   - <module>       | [31m[31m

* Resource error
  
  Cannot open URL
  | Traceback (most recent call last):
  |   File "/home/duckietown/scm/duckuments/mcdp/src/mcdp_docs/videos.py", line 110, in get_vimeo_info
  |     response = urllib2.urlopen(url)
  |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  |     return opener.open(url, data, timeout)
  |   File "/usr/lib/python2.7/urllib2.py", line 435, in open
  |     response = meth(req, response)
  |   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
  |     'http', request, response, code, msg, hdrs)
  |   File "/usr/lib/python2.7/urllib2.py", line 473, in error
  |     return self._call_chain(*args)
  |   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  |     result = func(*args)
  |   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
  |     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
  | HTTPError: HTTP Error 503: Service Unavailable[0m[0m
